-- Dream Big English Tuition - Supabase/PostgreSQL schema
-- Run this first in Supabase SQL Editor before importing data.

begin;

create table if not exists levels (
    id_level integer generated by default as identity primary key,
    level_name text not null,
    price double precision not null default 0
);

create table if not exists rooms (
    id_room integer generated by default as identity primary key,
    room_name text not null
);

create table if not exists schedules (
    id_schedule integer generated by default as identity primary key,
    start_time text not null,
    end_time text not null
);

create table if not exists tutors (
    id_tutor integer generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    phone_number text,
    address text
);

create table if not exists students (
    id_student integer generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    status integer not null default 1,
    phone text,
    dni text
);

create table if not exists teachers (
    id_teacher integer generated by default as identity primary key,
    first_name text not null,
    last_name text not null,
    phone text
);

create table if not exists student_tutor (
    id_student integer not null references students(id_student) on delete cascade,
    id_tutor integer not null references tutors(id_tutor) on delete cascade,
    primary key (id_student, id_tutor)
);

create table if not exists classes (
    id_class integer generated by default as identity primary key,
    id_level integer references levels(id_level),
    id_teacher integer references teachers(id_teacher),
    modality text
);

create table if not exists class_assignments (
    id_assignment integer generated by default as identity primary key,
    id_class integer references classes(id_class) on delete cascade,
    id_room integer references rooms(id_room),
    id_schedule integer references schedules(id_schedule),
    day_of_week integer not null,
    unique (id_room, id_schedule, day_of_week)
);

create table if not exists enrollments (
    id_enrollment integer generated by default as identity primary key,
    id_student integer references students(id_student) on delete cascade,
    id_class integer references classes(id_class) on delete cascade,
    school_year integer not null
);

create table if not exists academic_history (
    id_grade integer generated by default as identity primary key,
    id_student integer references students(id_student) on delete cascade,
    school_year integer not null,
    id_level_taken integer references levels(id_level),
    written_score double precision,
    oral_score double precision,
    intl_exam_info text,
    exam_date text
);

create table if not exists payments (
    id_payment integer generated by default as identity primary key,
    id_student integer references students(id_student) on delete cascade,
    year integer not null,
    month integer not null check (month between 1 and 12),
    amount double precision not null default 0,
    is_paid integer not null default 0 check (is_paid in (0, 1)),
    payment_date text,
    unique (id_student, month, year)
);

create index if not exists idx_student_lastname on students(last_name);
create unique index if not exists idx_students_dni on students(dni) where dni is not null and btrim(dni) <> '';
create index if not exists idx_tutor_lastname on tutors(last_name);
create index if not exists idx_payments_student_year on payments(id_student, year);
create index if not exists idx_enrollments_student_year on enrollments(id_student, school_year);
create index if not exists idx_class_assignments_day on class_assignments(day_of_week);

commit;
